config/routes.rb
Rails.application.routes.draw do

  resources :blocks
  resources :devices
  get 'static_pages/index'

  get 'static_pages/eula'
  get 'static_pages/proof'
  
  resources :improves
  resources :histories
  resources :souls
  resources :waves, :only => [:new, :create]

  # actual stuff
  root  'static_pages#index' # show the homepage in production mode
  get   'nearby',   to: 'devices#nearby' # returns how many devices nearby
  get   'device_history/:id',  to: 'histories#device_history'

  # test stuff
  get   'test',         to: 'test#index'
  post  'test',         to: 'test#sendToEveryone'
  post  'echo',         to: 'echo#reply'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/device.rb
class Device < ApplicationRecord

  # has_many :blocks
  has_many :histories, dependent: :destroy
  has_many :souls, dependent: :destroy
  # has_one :history
  validates :token, :latitude, :longitude, :radius, :os, presence: true
  validates :token, uniqueness: true

  #validate os enum
  enum oses: [ :ios, :android, :iosSimulator ]
  validates :os, inclusion: {in: Device.oses.keys}

  def is_blocking?(input_device) #does this device block input_device?
    return Block.where(blocker_id: self.id, blockee_id: input_device.id).exists?
  end

  def is_blocked_by?(input_device) #is this device blocked by input_device?
    return Block.where(blocker_id: input_device.id, blockee_id: self.id).exists?
  end

  def blocked?(input_device)
    if self.is_blocking?(input_device) || self.is_blocked_by?(input_device)
      return true
    end

    return false
  end

  def not_blocked?(input_device)
    return !blocked?(input_device)
  end

  def in_mutual_radius?(device) # check if this device is in the mutual radius another device
    # debug print
    # puts 'Self radius: ' + self.radius.to_s + "\tDevice radius: " + device.radius.to_s

    minRadius = [self.radius, device.radius].min

    deltaLat = self.latitude - device.latitude
    deltaLon = self.longitude - device.longitude

    distanceInDeg = (deltaLat * deltaLat + deltaLon * deltaLon) ** 0.5 #pythag hypotenuse

    # puts "Distance between two points (degrees): #{format('%.2f', distanceInDeg)}"
    # puts "Acceptance radius distance (degrees): #{format('%.2f', minRadius)}"
    return (distanceInDeg < minRadius)
  end

  def reaches?(input_device) #check if a soul sent from this device can be transmitted to another device
    return in_mutual_radius?(input_device) && not_blocked?(input_device)
  end

  def self.allRecentDevices
    return Device.where('updated_at > ?', 1.week.ago).order(:updated_at) #all devices updated in the last week
  end

  def otherRecentDevices
    return Device.where('updated_at > ?', 1.week.ago).where.not(id: self.id).order(:updated_at) #all devices except the caller updated in the last week
  end

  def devicesWithinMutualRange # returns an array of recent devices in the mutual radius including blocked devices
    devicesInRange = []

    otherRecentDevices.each do |device|
      if in_mutual_radius?(device)
        devicesInRange.append(device)
      end
    end

    return devicesInRange
  end

  # returns an array of all devices in mutual radius that did not block the sender and the sender did no block
  def broadcastableDevices
    allDevices = devicesWithinMutualRange
    devicesBlockingSender = Block.where(blockee_id: self.id).pluck(:blocker_id)
    devicesBlockedBySender = Block.where(blocker_id: self.id).pluck(:blockee_id)
    deviceIDsToRemove = devicesBlockingSender | devicesBlockedBySender

    devicesToRemove = Device.where(id: deviceIDsToRemove) #inner query gets all ids that blocked the broadcaster
    result = allDevices - devicesToRemove

    # puts allDevices.count.to_s + " other devices within mutual range, " + result.count.to_s + " other devices that are not blocked"
    return result
  end

  def nearbyDeviceCount #returns the number nearby devices non blocked updated in the last week
    return broadcastableDevices.count
  end

  def block (blockee)
    #make a new block object
    Block.create(blocker_id: self.id, blockee_id: blockee.id)
  end

end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token, only: [:create, :update] #for dev only, disables authenticity checking on create/update

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        #format.json { render json: @device.errors, status: :unprocessable_entity }

        jsonDevice = Device.find_by_token(@device.token)
        if jsonDevice.nil?
          render json: badRequest, status: :unprocessable_entity
          return
        end

        format.json { render json: Device.find_by_token(@device.token) } #return json of matching token rather than show error
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /nearby/?latitude=49.3&longitude=-122.9&radius=0.1&deviceid=SSSSSSSS
  def nearby
    if validParams?(params)
      render json: deviceCount(params)
    else
      render json: badRequest, status: :unprocessable_entity
    end
  end

  def badRequest
    {message: "bad request"}
  end

  def validParams?(params)
    return params[:latitude] && params[:longitude] && params[:radius] && params[:token] #check if we're getting extra params
  end

  def deviceCount(params)
    @device = Device.find_by_token(params[:token])
    @device.update(latitude: params[:latitude], longitude: params[:longitude], radius: params[:radius])
    {nearby: @device.nearbyDeviceCount}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:token, :latitude, :longitude, :radius, :os)
    end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_for(device) do |f| %>
  <% if device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :token %>
    <%= f.text_field :token %>
  </div>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="field">
    <%= f.label :radius %>
    <%= f.text_field :radius %>
  </div>

  <div class="field">
    <%= f.label :os %>
    <%= f.text_field :os %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing Device</h1>

<%= render 'form', device: @device %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Devices</h1>

<table>
  <thead>
    <tr>
      <th>Token</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Radius</th>
      <th>Os</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= device.token %></td>
        <td><%= device.latitude %></td>
        <td><%= device.longitude %></td>
        <td><%= device.radius %></td>
        <td><%= device.os %></td>
        <td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device', new_device_path %>

app/views/devices/new.html.erb
<h1>New Device</h1>

<%= render 'form', device: @device %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Token:</strong>
  <%= @device.token %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @device.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @device.longitude %>
</p>

<p>
  <strong>Radius:</strong>
  <%= @device.radius %>
</p>

<p>
  <strong>Os:</strong>
  <%= @device.os %>
</p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>