config/routes.rb
Rails.application.routes.draw do

  resources :blocks
  resources :devices
  get 'static_pages/index'

  get 'static_pages/eula'
  get 'static_pages/proof'
  
  resources :improves
  resources :histories
  resources :souls
  resources :waves, :only => [:new, :create]

  # actual stuff
  root  'static_pages#index' # show the homepage in production mode
  get   'nearby',   to: 'devices#nearby' # returns how many devices nearby
  get   'device_history/:id',  to: 'histories#device_history'

  # test stuff
  get   'test',         to: 'test#index'
  post  'test',         to: 'test#sendToEveryone'
  post  'echo',         to: 'echo#reply'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/improve.rb
class Improve < ApplicationRecord
end

app/controllers/improves_controller.rb
class ImprovesController < ApplicationController
  before_action :set_improve, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token, only: [:create, :update] #for dev only, disables authenticity checking on create/update
  
  # GET /improves
  # GET /improves.json
  def index
    @improves = Improve.all
  end

  # GET /improves/1
  # GET /improves/1.json
  def show
  end

  # GET /improves/new
  def new
    @improve = Improve.new
  end

  # GET /improves/1/edit
  def edit
  end

  # POST /improves
  # POST /improves.json
  def create
    @improve = Improve.new(improve_params)

    respond_to do |format|
      if @improve.save
        format.html { redirect_to @improve, notice: 'Improve was successfully created.' }
        format.json { render :show, status: :created, location: @improve }
      else
        format.html { render :new }
        format.json { render json: @improve.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /improves/1
  # PATCH/PUT /improves/1.json
  def update
    respond_to do |format|
      if @improve.update(improve_params)
        format.html { redirect_to @improve, notice: 'Improve was successfully updated.' }
        format.json { render :show, status: :ok, location: @improve }
      else
        format.html { render :edit }
        format.json { render json: @improve.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /improves/1
  # DELETE /improves/1.json
  def destroy
    @improve.destroy
    respond_to do |format|
      format.html { redirect_to improves_url, notice: 'Improve was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_improve
      @improve = Improve.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def improve_params
      params.require(:improve).permit(:soulType, :s3Key, :epoch, :latitude, :longitude, :radius)
    end
end

app/helpers/improves_helper.rb
module ImprovesHelper
end

app/views/improves/_form.html.erb
<%= form_for(improve) do |f| %>
  <% if improve.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(improve.errors.count, "error") %> prohibited this improve from being saved:</h2>

      <ul>
      <% improve.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :soulType %>
    <%= f.text_field :soulType %>
  </div>

  <div class="field">
    <%= f.label :s3Key %>
    <%= f.text_field :s3Key %>
  </div>

  <div class="field">
    <%= f.label :epoch %>
    <%= f.number_field :epoch %>
  </div>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="field">
    <%= f.label :radius %>
    <%= f.text_field :radius %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/improves/edit.html.erb
<h1>Editing Improve</h1>

<%= render 'form', improve: @improve %>

<%= link_to 'Show', @improve %> |
<%= link_to 'Back', improves_path %>

app/views/improves/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Improves</h1>

<table>
  <thead>
    <tr>
      <th>Soultype</th>
      <th>S3key</th>
      <th>Epoch</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Radius</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @improves.each do |improve| %>
      <tr>
        <td><%= improve.soulType %></td>
        <td><%= improve.s3Key %></td>
        <td><%= improve.epoch %></td>
        <td><%= improve.latitude %></td>
        <td><%= improve.longitude %></td>
        <td><%= improve.radius %></td>
        <td><%= link_to 'Show', improve %></td>
        <td><%= link_to 'Edit', edit_improve_path(improve) %></td>
        <td><%= link_to 'Destroy', improve, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Improve', new_improve_path %>

app/views/improves/new.html.erb
<h1>New Improve</h1>

<%= render 'form', improve: @improve %>

<%= link_to 'Back', improves_path %>

app/views/improves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Soultype:</strong>
  <%= @improve.soulType %>
</p>

<p>
  <strong>S3key:</strong>
  <%= @improve.s3Key %>
</p>

<p>
  <strong>Epoch:</strong>
  <%= @improve.epoch %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @improve.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @improve.longitude %>
</p>

<p>
  <strong>Radius:</strong>
  <%= @improve.radius %>
</p>

<%= link_to 'Edit', edit_improve_path(@improve) %> |
<%= link_to 'Back', improves_path %>